import { Ship, LayoutDashboard, Package, ShoppingCart, DollarSign, FileText, BarChart3, Settings, LogOut, Search, Bell, User as UserIcon, Menu, X, Plus, Trash2, Edit, ChevronRight, AlertTriangle, TrendingUp, TrendingDown, Clock, Eye, Download } from 'lucide-react';

export const Icon = {
  Logo: Ship,
  Dashboard: LayoutDashboard,
  Inventory: Package,
  Buy: ShoppingCart,
  Sell: DollarSign,
  Invoices: FileText,
  Reports: BarChart3,
  Settings: Settings,
  Logout: LogOut,
  Search: Search,
  Bell: Bell,
  User: UserIcon,
  Menu: Menu,
  Close: X,
  Plus: Plus,
  Delete: Trash2,
  Edit: Edit,
  ChevronRight: ChevronRight,
  Alert: AlertTriangle,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  History: Clock,
  Eye: Eye,
  FileText: FileText,
  Download: Download,
};
